### ISSUE TITLE
How do you expect us to create the apk?

### ISSUE THREAD

**Issue by emrednn** [DEVELOPERcreatinon/Brawl-Stars-Server-V28#1]

**Comment by DEVELOPERcreatinon** [comment]
Sorry, I'll leave a link to the apk from Google Drive soon

**Comment by emrednn** [comment]
> Sorry, I'll leave a link to the apk from Google Drive soon

Thanks so much I'll be waiting.

**Comment by DEVELOPERcreatinon** [comment]
I added a link to Google Drive
