### ISSUE TITLE
Important Issues

### ISSUE THREAD

**Issue by kubune** [DEVELOPERcreatinon/Brawl-Stars-Server-V28#2]
The server won't work due to server packets like FriendOnlineStatusMessage and TopClubsLeaderboardMessage not working. (They have wrong data, please update the files).

**Comment by DEVELOPERcreatinon** [comment]
I'll update them soon, thanks for pointing out the mistake.

**Comment by DEVELOPERcreatinon** [comment]
I'll update them soon, thanks for pointing out the mistake.

**Comment by DEVELOPERcreatinon** [comment]
Please specify the path to the files

**Comment by DEVELOPERcreatinon** [comment]
я исправил их
